[package]
name = "land-native"
version = "0.1.0"
edition = "2024"
rust-version = "1.96.1"

[lib]
crate-type = ["cdylib"]

[dependencies]
wl-android-common = { path = "../../crates/wl-android-common" }
jni = "0.21"
libc = "0.2"
log = "0.4"
nix = { version = "0.31", features = ["socket", "uio"] }

[target.'cfg(target_os = "android")'.dependencies]
ash = "0.38"
ndk = "0.9"
ndk-sys = "0.6"
android_logger = "0.14"

[profile.release]
debug = 1

[build-dependencies]
cc = { version = "1", features = ["parallel"] }
